### PR TITLE
fix(core): do not collect component twice, closes #177

### LINKED ISSUE #177: [bug] `no-missing-component-display-name` not work with early return component
### Describe the bug

The following code should not report an error

```tsx
import { forwardRef, ReactNode } from 'react';

interface Props {
  children?: ReactNode;
}
export type Ref = HTMLButtonElement;

const FancyButton = forwardRef<Ref, Props>((props, ref) => {
  // It's works without this
  if (!props.children) return null;
  return (
    <button ref={ref} className="MyClassName" type="button">
      {props.children}
      hell
    </button>
  );
});

FancyButton.displayName = 'FancyButton';

export default function App() {
  return <FancyButton />;
}
```

```
/home/projects/vitejs-vite-bngjjk/src/app.tsx
  8:44  warning  no missing display name  @eslint-react/react/no-missing-component-display-name

✖ 1 problem (0 errors, 1 warning)
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-bngjjk?file=src%2Fapp.tsx

### Expected behavior

_No response_

### Platform and versions

```Text
In stackblitz with "@eslint-react/eslint-plugin": "^0.8.9"
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hyoban**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist

- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by Rel1cx** [comment]
Could you first report a bug and provide a minimal reproduction?

**Comment by Rel1cx** [comment]
If PR is a bugfix, it's better to associate it with an issue, or create it if there is no existing issue, thanks a lot!

**Comment by Rel1cx** [comment]
This solution is not good enough, for this case, a tuple can be used as a stack item to avoid the need to find each time.

**Comment by Rel1cx** [comment]
I've opened a draft PR #178 and you can either update the changes to this PR to that, or just let me merge that in.

**Comment by hyoban** [comment]
Close this, you can just merge #178

**Pull request closed without merging**
