### PR TITLE
build: remove patch of eslint-doc-generator

### PR DESCRIPTION
**Pull request by hyoban**
### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [x] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist

- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] I have added a convincing reason for adding this feature, if necessary

### Other information

https://github.com/bmish/eslint-doc-generator/pull/502 is merged

### CODE REVIEW

**Comment by hyoban** [comment]
Can you just protect the `main` branch and allow me to create and push branches directly to this repository, otherwise I would need to keep a fork?

**Comment by Rel1cx** [comment]
eslint-doc-generator will be removed from the project in a few days.

1. we don't rely on it much
2. the tool doesn't fit our project structure
3. future rules documentation will be written in mdx, this plugin can't and is not suitable to provide support for it

**Comment by Rel1cx** [comment]
> Can you just protect the `main` branch and allow me to create and push branches directly to this repository, otherwise I would need to keep a fork?

Thanks for the advice, no.

**Comment by Rel1cx** [comment]
> > Can you just protect the `main` branch and allow me to create and push branches directly to this repository, otherwise I would need to keep a fork?
> 
> Thanks for the advice, but I'm afraid I can't do that now.

Please give me some time to sort out some design matters. Thank you very much🙏.

**Pull request closed without merging**
