### PR TITLE
refactor: update the default behavior of import check, closes #858

### LINKED ISSUE #858: [bug] [@eslint-react/naming-convention/use-state] does not enforce symmetric names
### Describe the bug

[Documentation](https://eslint-react.xyz/docs/rules/naming-convention-use-state) states to check symmetric naming, but
```js
const [state, setValue] = useState(0);
```
passes.

### Reproduction

_No response_

### Expected behavior

Fails because of "state" vs. "setValue" naming mismatch, as `react/hook-use-state` does.

### Platform and versions

```Text
eslint: 9.15.0
@eslint-react/eslint-plugin: 1.16.1
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Rel1cx**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist

- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Comment by kachkaev** [comment]
👋 @Rel1cx! I think I’ve noticed an unexpected issue in `@eslint-react/no-array-index-key`, and bisecting releases has pointed to this commit.

In `1.16.2-beta.6` code like this produces a linting error, which is expected:

```ts
foo.bar.map((value, index) => <MyComponent key={index} />);
```

However, after upgrading to `1.16.2-beta.7`, the issue is no longer reported.

If I replace nesting with `const { bar } = foo` and then call `bar.map` in JSX, `@eslint-react/no-array-index-key` works again as expected.

I am thinking of creating a new issue but in needs a reproduction and I don’t have time on it today. I’ve decided to ping you here first with my initial investigation to just sense-check what I observe. WDYT?

**Comment by Rel1cx** [comment]
> 👋 @Rel1cx! I think I’ve noticed new issue in `@eslint-react/no-array-index-key`, and bisecting has pointed me to this commit.
> 
> In `1.16.2-beta.6` code like this produces a linting error, which is expected:
> 
> ```tsx
> foo.bar.map((value, index) => <MyComponent key={index} />);
> ```
> 
> However, after upgrading to `1.16.2-beta.7`, the issue is no longer reported.
> 
> If I replace property chaining with `const { bar } = foo;` and then call `bar.map(...)` in JSX, `@eslint-react/no-array-index-key` is reported again as expected.
> 
> I am thinking of creating a new issue but in needs a proper reproduction and I don’t have time on it today. I’ve decided to ping you here first with my initial investigation to just sense-check what I observe. WDYT?

Hello! I just reviewed the code and have pinpointed the issue and started fixing it. Your initial investigation was correct and helpful; this commit indeed introduced the problem. Thank you for providing the information.

**Comment by kachkaev** [comment]
Great, thanks for responding so quickly @Rel1cx! I just tried `1.17.3-beta.1` which included https://github.com/Rel1cx/eslint-react/pull/868 and it worked 🎉

**Comment by kachkaev** [comment]
Another thing that I noticed after upgrading from `1.16.1` to newer versions is `@eslint-react/prefer-read-only-props` triggering everywhere. We use this definition style for components:

```tsx
import * as React from 'react';

export const Foo: React.FunctionComponent<{
  bar: string;
}> = ({ bar }) => {
  return <></>;
};
```


The rule I believe that it’s actually fixing a problem rather introducing a new one. The rule is included in [`recommended-type-checked`](https://github.com/Rel1cx/eslint-react/blob/87ca237695280371078c9cc602b64c6826045ff2/packages/plugins/eslint-plugin/src/configs/recommended-type-checked.ts#L10) but it was not triggering for us, probably until this PR.

No action needed on this one, just an FYI.

**Pull request merged**
